artifact_location: /Users/isabellevea/Documents/_GitHub/divvy-mlops/deployment/random-forest-regressor/0
creation_time: 1723578696021
experiment_id: '0'
last_update_time: 1723578696021
lifecycle_stage: active
name: Default
