# config file version
apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: divvy-monitoring
    user: postgres
    secureJsonData: 
      password: 'example'
    jsonData:
      sslmode: 'disable'
